// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Management.Api.DatabaseContext;

#nullable disable

namespace Product.Management.Api.Migrations
{
    [DbContext(typeof(ProductManagementContext))]
    [Migration("20241121052937_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.Management.Api.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("float");

                    b.Property<double>("Units")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProductMgmt");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Dairy Products",
                            DateCreated = new DateTime(2024, 11, 21, 10, 59, 36, 618, DateTimeKind.Local).AddTicks(988),
                            DateModified = new DateTime(2024, 11, 21, 10, 59, 36, 618, DateTimeKind.Local).AddTicks(1004),
                            Description = "Amul Diced Cheese Blend Mozzeralla Cheddar",
                            Name = "Cheese",
                            ProductPrice = 116m,
                            ProductWeight = 200.0,
                            Units = 20.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
